version: '3.8'

services:
  redis:
    # Sugestão: Imagem alpine, menor e mais leve. Versão 7 especificada.
    image: redis:7-alpine
    # Sugestão: Nome genérico para um serviço compartilhado.
    container_name: redis-shared
    restart: always
    # Comando para iniciar o Redis exigindo a senha definida no .env.
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Conecta o serviço à nossa rede compartilhada.
    networks:
      - coral-home-net

volumes:
  redis_data:
    driver: local

networks:
  coral-home-net:
    external: true